version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
      - DB_NAME=sequences-db
      - SECRET_KEY=UhYDe8hw1B
      - PORT=8085
      - EXPIRATION_SECONDS=600
    ports:
      - '8085:8085'
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge